/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppWiringHarnessRouteImport } from './routes/_app/wiring-harness'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppMarketplaceRouteImport } from './routes/_app/marketplace'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppJourneysRouteImport } from './routes/_app/journeys'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppGalleryRouteImport } from './routes/_app/gallery'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppCarsRouteImport } from './routes/_app/cars'
import { Route as AppJourneysIndexRouteImport } from './routes/_app/journeys/index'
import { Route as AppCarsIndexRouteImport } from './routes/_app/cars/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppMeJourneysRouteImport } from './routes/_app/me/journeys'
import { Route as AppMeCarsRouteImport } from './routes/_app/me/cars'
import { Route as AppMeJourneysIndexRouteImport } from './routes/_app/me/journeys/index'
import { Route as AppMeCarsIndexRouteImport } from './routes/_app/me/cars/index'
import { Route as AppJourneysJourneyIdIndexRouteImport } from './routes/_app/journeys/$journeyId/index'
import { Route as AppMeCarsNewRouteImport } from './routes/_app/me/cars/new'
import { Route as AppMeCarsCarIdIndexRouteImport } from './routes/_app/me/cars/$carId/index'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppWiringHarnessRoute = AppWiringHarnessRouteImport.update({
  id: '/wiring-harness',
  path: '/wiring-harness',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneysRoute = AppJourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCarsRoute = AppCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneysIndexRoute = AppJourneysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJourneysRoute,
} as any)
const AppCarsIndexRoute = AppCarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCarsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeJourneysRoute = AppMeJourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => AppMeRoute,
} as any)
const AppMeCarsRoute = AppMeCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AppMeRoute,
} as any)
const AppMeJourneysIndexRoute = AppMeJourneysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeJourneysRoute,
} as any)
const AppMeCarsIndexRoute = AppMeCarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeCarsRoute,
} as any)
const AppJourneysJourneyIdIndexRoute =
  AppJourneysJourneyIdIndexRouteImport.update({
    id: '/$journeyId/',
    path: '/$journeyId/',
    getParentRoute: () => AppJourneysRoute,
  } as any)
const AppMeCarsNewRoute = AppMeCarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMeCarsRoute,
} as any)
const AppMeCarsCarIdIndexRoute = AppMeCarsCarIdIndexRouteImport.update({
  id: '/$carId/',
  path: '/$carId/',
  getParentRoute: () => AppMeCarsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/cars': typeof AppCarsRouteWithChildren
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/explore': typeof AppExploreRoute
  '/feed': typeof AppFeedRoute
  '/gallery': typeof AppGalleryRoute
  '/inventory': typeof AppInventoryRoute
  '/journeys': typeof AppJourneysRouteWithChildren
  '/knowledge': typeof AppKnowledgeRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/me': typeof AppMeRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/wiring-harness': typeof AppWiringHarnessRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/me/cars': typeof AppMeCarsRouteWithChildren
  '/me/journeys': typeof AppMeJourneysRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cars/': typeof AppCarsIndexRoute
  '/journeys/': typeof AppJourneysIndexRoute
  '/me/cars/new': typeof AppMeCarsNewRoute
  '/journeys/$journeyId/': typeof AppJourneysJourneyIdIndexRoute
  '/me/cars/': typeof AppMeCarsIndexRoute
  '/me/journeys/': typeof AppMeJourneysIndexRoute
  '/me/cars/$carId/': typeof AppMeCarsCarIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/explore': typeof AppExploreRoute
  '/feed': typeof AppFeedRoute
  '/gallery': typeof AppGalleryRoute
  '/inventory': typeof AppInventoryRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/me': typeof AppMeRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/wiring-harness': typeof AppWiringHarnessRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cars': typeof AppCarsIndexRoute
  '/journeys': typeof AppJourneysIndexRoute
  '/me/cars/new': typeof AppMeCarsNewRoute
  '/journeys/$journeyId': typeof AppJourneysJourneyIdIndexRoute
  '/me/cars': typeof AppMeCarsIndexRoute
  '/me/journeys': typeof AppMeJourneysIndexRoute
  '/me/cars/$carId': typeof AppMeCarsCarIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/cars': typeof AppCarsRouteWithChildren
  '/_app/community': typeof AppCommunityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/gallery': typeof AppGalleryRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/journeys': typeof AppJourneysRouteWithChildren
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/me': typeof AppMeRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/wiring-harness': typeof AppWiringHarnessRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_app/me/cars': typeof AppMeCarsRouteWithChildren
  '/_app/me/journeys': typeof AppMeJourneysRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/cars/': typeof AppCarsIndexRoute
  '/_app/journeys/': typeof AppJourneysIndexRoute
  '/_app/me/cars/new': typeof AppMeCarsNewRoute
  '/_app/journeys/$journeyId/': typeof AppJourneysJourneyIdIndexRoute
  '/_app/me/cars/': typeof AppMeCarsIndexRoute
  '/_app/me/journeys/': typeof AppMeJourneysIndexRoute
  '/_app/me/cars/$carId/': typeof AppMeCarsCarIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/feed'
    | '/gallery'
    | '/inventory'
    | '/journeys'
    | '/knowledge'
    | '/marketplace'
    | '/me'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/wiring-harness'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/me/cars'
    | '/me/journeys'
    | '/api/auth/$'
    | '/cars/'
    | '/journeys/'
    | '/me/cars/new'
    | '/journeys/$journeyId/'
    | '/me/cars/'
    | '/me/journeys/'
    | '/me/cars/$carId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/feed'
    | '/gallery'
    | '/inventory'
    | '/knowledge'
    | '/marketplace'
    | '/me'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/wiring-harness'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/api/auth/$'
    | '/cars'
    | '/journeys'
    | '/me/cars/new'
    | '/journeys/$journeyId'
    | '/me/cars'
    | '/me/journeys'
    | '/me/cars/$carId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_marketing'
    | '/_app/cars'
    | '/_app/community'
    | '/_app/dashboard'
    | '/_app/events'
    | '/_app/explore'
    | '/_app/feed'
    | '/_app/gallery'
    | '/_app/inventory'
    | '/_app/journeys'
    | '/_app/knowledge'
    | '/_app/marketplace'
    | '/_app/me'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/subscription'
    | '/_app/wiring-harness'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_marketing/'
    | '/_app/me/cars'
    | '/_app/me/journeys'
    | '/api/auth/$'
    | '/_app/cars/'
    | '/_app/journeys/'
    | '/_app/me/cars/new'
    | '/_app/journeys/$journeyId/'
    | '/_app/me/cars/'
    | '/_app/me/journeys/'
    | '/_app/me/cars/$carId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/wiring-harness': {
      id: '/_app/wiring-harness'
      path: '/wiring-harness'
      fullPath: '/wiring-harness'
      preLoaderRoute: typeof AppWiringHarnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journeys': {
      id: '/_app/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof AppJourneysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery': {
      id: '/_app/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cars': {
      id: '/_app/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof AppCarsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journeys/': {
      id: '/_app/journeys/'
      path: '/'
      fullPath: '/journeys/'
      preLoaderRoute: typeof AppJourneysIndexRouteImport
      parentRoute: typeof AppJourneysRoute
    }
    '/_app/cars/': {
      id: '/_app/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof AppCarsIndexRouteImport
      parentRoute: typeof AppCarsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/me/journeys': {
      id: '/_app/me/journeys'
      path: '/journeys'
      fullPath: '/me/journeys'
      preLoaderRoute: typeof AppMeJourneysRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/_app/me/cars': {
      id: '/_app/me/cars'
      path: '/cars'
      fullPath: '/me/cars'
      preLoaderRoute: typeof AppMeCarsRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/_app/me/journeys/': {
      id: '/_app/me/journeys/'
      path: '/'
      fullPath: '/me/journeys/'
      preLoaderRoute: typeof AppMeJourneysIndexRouteImport
      parentRoute: typeof AppMeJourneysRoute
    }
    '/_app/me/cars/': {
      id: '/_app/me/cars/'
      path: '/'
      fullPath: '/me/cars/'
      preLoaderRoute: typeof AppMeCarsIndexRouteImport
      parentRoute: typeof AppMeCarsRoute
    }
    '/_app/journeys/$journeyId/': {
      id: '/_app/journeys/$journeyId/'
      path: '/$journeyId'
      fullPath: '/journeys/$journeyId/'
      preLoaderRoute: typeof AppJourneysJourneyIdIndexRouteImport
      parentRoute: typeof AppJourneysRoute
    }
    '/_app/me/cars/new': {
      id: '/_app/me/cars/new'
      path: '/new'
      fullPath: '/me/cars/new'
      preLoaderRoute: typeof AppMeCarsNewRouteImport
      parentRoute: typeof AppMeCarsRoute
    }
    '/_app/me/cars/$carId/': {
      id: '/_app/me/cars/$carId/'
      path: '/$carId'
      fullPath: '/me/cars/$carId/'
      preLoaderRoute: typeof AppMeCarsCarIdIndexRouteImport
      parentRoute: typeof AppMeCarsRoute
    }
  }
}

interface AppCarsRouteChildren {
  AppCarsIndexRoute: typeof AppCarsIndexRoute
}

const AppCarsRouteChildren: AppCarsRouteChildren = {
  AppCarsIndexRoute: AppCarsIndexRoute,
}

const AppCarsRouteWithChildren =
  AppCarsRoute._addFileChildren(AppCarsRouteChildren)

interface AppJourneysRouteChildren {
  AppJourneysIndexRoute: typeof AppJourneysIndexRoute
  AppJourneysJourneyIdIndexRoute: typeof AppJourneysJourneyIdIndexRoute
}

const AppJourneysRouteChildren: AppJourneysRouteChildren = {
  AppJourneysIndexRoute: AppJourneysIndexRoute,
  AppJourneysJourneyIdIndexRoute: AppJourneysJourneyIdIndexRoute,
}

const AppJourneysRouteWithChildren = AppJourneysRoute._addFileChildren(
  AppJourneysRouteChildren,
)

interface AppMeCarsRouteChildren {
  AppMeCarsNewRoute: typeof AppMeCarsNewRoute
  AppMeCarsIndexRoute: typeof AppMeCarsIndexRoute
  AppMeCarsCarIdIndexRoute: typeof AppMeCarsCarIdIndexRoute
}

const AppMeCarsRouteChildren: AppMeCarsRouteChildren = {
  AppMeCarsNewRoute: AppMeCarsNewRoute,
  AppMeCarsIndexRoute: AppMeCarsIndexRoute,
  AppMeCarsCarIdIndexRoute: AppMeCarsCarIdIndexRoute,
}

const AppMeCarsRouteWithChildren = AppMeCarsRoute._addFileChildren(
  AppMeCarsRouteChildren,
)

interface AppMeJourneysRouteChildren {
  AppMeJourneysIndexRoute: typeof AppMeJourneysIndexRoute
}

const AppMeJourneysRouteChildren: AppMeJourneysRouteChildren = {
  AppMeJourneysIndexRoute: AppMeJourneysIndexRoute,
}

const AppMeJourneysRouteWithChildren = AppMeJourneysRoute._addFileChildren(
  AppMeJourneysRouteChildren,
)

interface AppMeRouteChildren {
  AppMeCarsRoute: typeof AppMeCarsRouteWithChildren
  AppMeJourneysRoute: typeof AppMeJourneysRouteWithChildren
}

const AppMeRouteChildren: AppMeRouteChildren = {
  AppMeCarsRoute: AppMeCarsRouteWithChildren,
  AppMeJourneysRoute: AppMeJourneysRouteWithChildren,
}

const AppMeRouteWithChildren = AppMeRoute._addFileChildren(AppMeRouteChildren)

interface AppRouteChildren {
  AppCarsRoute: typeof AppCarsRouteWithChildren
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFeedRoute: typeof AppFeedRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppJourneysRoute: typeof AppJourneysRouteWithChildren
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMeRoute: typeof AppMeRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppWiringHarnessRoute: typeof AppWiringHarnessRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarsRoute: AppCarsRouteWithChildren,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRoute,
  AppExploreRoute: AppExploreRoute,
  AppFeedRoute: AppFeedRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppJourneysRoute: AppJourneysRouteWithChildren,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMeRoute: AppMeRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppWiringHarnessRoute: AppWiringHarnessRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
