/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppWiringHarnessRouteImport } from './routes/_app/wiring-harness'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppMarketplaceRouteImport } from './routes/_app/marketplace'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppJourneysRouteImport } from './routes/_app/journeys'
import { Route as AppGalleryRouteImport } from './routes/_app/gallery'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppCarsRouteImport } from './routes/_app/cars'
import { Route as AppMeIndexRouteImport } from './routes/_app/me/index'
import { Route as AppJourneysIndexRouteImport } from './routes/_app/journeys/index'
import { Route as AppCarsIndexRouteImport } from './routes/_app/cars/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersUsernameRouteImport } from './routes/_app/users/$username'
import { Route as AppMeSubscriptionRouteImport } from './routes/_app/me/subscription'
import { Route as AppMeSettingsRouteImport } from './routes/_app/me/settings'
import { Route as AppMeNotificationsRouteImport } from './routes/_app/me/notifications'
import { Route as AppMeInventoryRouteImport } from './routes/_app/me/inventory'
import { Route as AppUsersUsernameIndexRouteImport } from './routes/_app/users/$username/index'
import { Route as AppUsersUsernameJourneysRouteImport } from './routes/_app/users/$username/journeys'
import { Route as AppUsersUsernameCarsRouteImport } from './routes/_app/users/$username/cars'
import { Route as AppUsersUsernameJourneysIndexRouteImport } from './routes/_app/users/$username/journeys/index'
import { Route as AppUsersUsernameCarsIndexRouteImport } from './routes/_app/users/$username/cars/index'
import { Route as AppUsersUsernameJourneysSlugRouteImport } from './routes/_app/users/$username/journeys/$slug'
import { Route as AppUsersUsernameCarsNewRouteImport } from './routes/_app/users/$username/cars/new'
import { Route as AppUsersUsernameCarsSlugRouteImport } from './routes/_app/users/$username/cars/$slug'
import { Route as AppUsersUsernameJourneysSlugIndexRouteImport } from './routes/_app/users/$username/journeys/$slug/index'
import { Route as AppUsersUsernameCarsSlugIndexRouteImport } from './routes/_app/users/$username/cars/$slug/index'
import { Route as AppUsersUsernameCarsSlugEditRouteImport } from './routes/_app/users/$username/cars/$slug/edit'
import { Route as AppUsersUsernameJourneysSlugV2IndexRouteImport } from './routes/_app/users/$username/journeys/$slug/v2/index'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppWiringHarnessRoute = AppWiringHarnessRouteImport.update({
  id: '/wiring-harness',
  path: '/wiring-harness',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneysRoute = AppJourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCarsRoute = AppCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AppRoute,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeRoute,
} as any)
const AppJourneysIndexRoute = AppJourneysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJourneysRoute,
} as any)
const AppCarsIndexRoute = AppCarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCarsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUsernameRoute = AppUsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppMeSubscriptionRoute = AppMeSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppMeRoute,
} as any)
const AppMeSettingsRoute = AppMeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMeRoute,
} as any)
const AppMeNotificationsRoute = AppMeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppMeRoute,
} as any)
const AppMeInventoryRoute = AppMeInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppMeRoute,
} as any)
const AppUsersUsernameIndexRoute = AppUsersUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersUsernameRoute,
} as any)
const AppUsersUsernameJourneysRoute =
  AppUsersUsernameJourneysRouteImport.update({
    id: '/journeys',
    path: '/journeys',
    getParentRoute: () => AppUsersUsernameRoute,
  } as any)
const AppUsersUsernameCarsRoute = AppUsersUsernameCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AppUsersUsernameRoute,
} as any)
const AppUsersUsernameJourneysIndexRoute =
  AppUsersUsernameJourneysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppUsersUsernameJourneysRoute,
  } as any)
const AppUsersUsernameCarsIndexRoute =
  AppUsersUsernameCarsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppUsersUsernameCarsRoute,
  } as any)
const AppUsersUsernameJourneysSlugRoute =
  AppUsersUsernameJourneysSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AppUsersUsernameJourneysRoute,
  } as any)
const AppUsersUsernameCarsNewRoute = AppUsersUsernameCarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppUsersUsernameCarsRoute,
} as any)
const AppUsersUsernameCarsSlugRoute =
  AppUsersUsernameCarsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AppUsersUsernameCarsRoute,
  } as any)
const AppUsersUsernameJourneysSlugIndexRoute =
  AppUsersUsernameJourneysSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppUsersUsernameJourneysSlugRoute,
  } as any)
const AppUsersUsernameCarsSlugIndexRoute =
  AppUsersUsernameCarsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppUsersUsernameCarsSlugRoute,
  } as any)
const AppUsersUsernameCarsSlugEditRoute =
  AppUsersUsernameCarsSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppUsersUsernameCarsSlugRoute,
  } as any)
const AppUsersUsernameJourneysSlugV2IndexRoute =
  AppUsersUsernameJourneysSlugV2IndexRouteImport.update({
    id: '/v2/',
    path: '/v2/',
    getParentRoute: () => AppUsersUsernameJourneysSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/cars': typeof AppCarsRouteWithChildren
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/explore': typeof AppExploreRoute
  '/feed': typeof AppFeedRoute
  '/gallery': typeof AppGalleryRoute
  '/journeys': typeof AppJourneysRouteWithChildren
  '/knowledge': typeof AppKnowledgeRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/me': typeof AppMeRouteWithChildren
  '/wiring-harness': typeof AppWiringHarnessRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/me/inventory': typeof AppMeInventoryRoute
  '/me/notifications': typeof AppMeNotificationsRoute
  '/me/settings': typeof AppMeSettingsRoute
  '/me/subscription': typeof AppMeSubscriptionRoute
  '/users/$username': typeof AppUsersUsernameRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cars/': typeof AppCarsIndexRoute
  '/journeys/': typeof AppJourneysIndexRoute
  '/me/': typeof AppMeIndexRoute
  '/users/$username/cars': typeof AppUsersUsernameCarsRouteWithChildren
  '/users/$username/journeys': typeof AppUsersUsernameJourneysRouteWithChildren
  '/users/$username/': typeof AppUsersUsernameIndexRoute
  '/users/$username/cars/$slug': typeof AppUsersUsernameCarsSlugRouteWithChildren
  '/users/$username/cars/new': typeof AppUsersUsernameCarsNewRoute
  '/users/$username/journeys/$slug': typeof AppUsersUsernameJourneysSlugRouteWithChildren
  '/users/$username/cars/': typeof AppUsersUsernameCarsIndexRoute
  '/users/$username/journeys/': typeof AppUsersUsernameJourneysIndexRoute
  '/users/$username/cars/$slug/edit': typeof AppUsersUsernameCarsSlugEditRoute
  '/users/$username/cars/$slug/': typeof AppUsersUsernameCarsSlugIndexRoute
  '/users/$username/journeys/$slug/': typeof AppUsersUsernameJourneysSlugIndexRoute
  '/users/$username/journeys/$slug/v2/': typeof AppUsersUsernameJourneysSlugV2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/explore': typeof AppExploreRoute
  '/feed': typeof AppFeedRoute
  '/gallery': typeof AppGalleryRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/wiring-harness': typeof AppWiringHarnessRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/me/inventory': typeof AppMeInventoryRoute
  '/me/notifications': typeof AppMeNotificationsRoute
  '/me/settings': typeof AppMeSettingsRoute
  '/me/subscription': typeof AppMeSubscriptionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cars': typeof AppCarsIndexRoute
  '/journeys': typeof AppJourneysIndexRoute
  '/me': typeof AppMeIndexRoute
  '/users/$username': typeof AppUsersUsernameIndexRoute
  '/users/$username/cars/new': typeof AppUsersUsernameCarsNewRoute
  '/users/$username/cars': typeof AppUsersUsernameCarsIndexRoute
  '/users/$username/journeys': typeof AppUsersUsernameJourneysIndexRoute
  '/users/$username/cars/$slug/edit': typeof AppUsersUsernameCarsSlugEditRoute
  '/users/$username/cars/$slug': typeof AppUsersUsernameCarsSlugIndexRoute
  '/users/$username/journeys/$slug': typeof AppUsersUsernameJourneysSlugIndexRoute
  '/users/$username/journeys/$slug/v2': typeof AppUsersUsernameJourneysSlugV2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/cars': typeof AppCarsRouteWithChildren
  '/_app/community': typeof AppCommunityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/gallery': typeof AppGalleryRoute
  '/_app/journeys': typeof AppJourneysRouteWithChildren
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/me': typeof AppMeRouteWithChildren
  '/_app/wiring-harness': typeof AppWiringHarnessRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_app/me/inventory': typeof AppMeInventoryRoute
  '/_app/me/notifications': typeof AppMeNotificationsRoute
  '/_app/me/settings': typeof AppMeSettingsRoute
  '/_app/me/subscription': typeof AppMeSubscriptionRoute
  '/_app/users/$username': typeof AppUsersUsernameRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/cars/': typeof AppCarsIndexRoute
  '/_app/journeys/': typeof AppJourneysIndexRoute
  '/_app/me/': typeof AppMeIndexRoute
  '/_app/users/$username/cars': typeof AppUsersUsernameCarsRouteWithChildren
  '/_app/users/$username/journeys': typeof AppUsersUsernameJourneysRouteWithChildren
  '/_app/users/$username/': typeof AppUsersUsernameIndexRoute
  '/_app/users/$username/cars/$slug': typeof AppUsersUsernameCarsSlugRouteWithChildren
  '/_app/users/$username/cars/new': typeof AppUsersUsernameCarsNewRoute
  '/_app/users/$username/journeys/$slug': typeof AppUsersUsernameJourneysSlugRouteWithChildren
  '/_app/users/$username/cars/': typeof AppUsersUsernameCarsIndexRoute
  '/_app/users/$username/journeys/': typeof AppUsersUsernameJourneysIndexRoute
  '/_app/users/$username/cars/$slug/edit': typeof AppUsersUsernameCarsSlugEditRoute
  '/_app/users/$username/cars/$slug/': typeof AppUsersUsernameCarsSlugIndexRoute
  '/_app/users/$username/journeys/$slug/': typeof AppUsersUsernameJourneysSlugIndexRoute
  '/_app/users/$username/journeys/$slug/v2/': typeof AppUsersUsernameJourneysSlugV2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/feed'
    | '/gallery'
    | '/journeys'
    | '/knowledge'
    | '/marketplace'
    | '/me'
    | '/wiring-harness'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/me/inventory'
    | '/me/notifications'
    | '/me/settings'
    | '/me/subscription'
    | '/users/$username'
    | '/api/auth/$'
    | '/cars/'
    | '/journeys/'
    | '/me/'
    | '/users/$username/cars'
    | '/users/$username/journeys'
    | '/users/$username/'
    | '/users/$username/cars/$slug'
    | '/users/$username/cars/new'
    | '/users/$username/journeys/$slug'
    | '/users/$username/cars/'
    | '/users/$username/journeys/'
    | '/users/$username/cars/$slug/edit'
    | '/users/$username/cars/$slug/'
    | '/users/$username/journeys/$slug/'
    | '/users/$username/journeys/$slug/v2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/feed'
    | '/gallery'
    | '/knowledge'
    | '/marketplace'
    | '/wiring-harness'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/me/inventory'
    | '/me/notifications'
    | '/me/settings'
    | '/me/subscription'
    | '/api/auth/$'
    | '/cars'
    | '/journeys'
    | '/me'
    | '/users/$username'
    | '/users/$username/cars/new'
    | '/users/$username/cars'
    | '/users/$username/journeys'
    | '/users/$username/cars/$slug/edit'
    | '/users/$username/cars/$slug'
    | '/users/$username/journeys/$slug'
    | '/users/$username/journeys/$slug/v2'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_marketing'
    | '/_app/cars'
    | '/_app/community'
    | '/_app/dashboard'
    | '/_app/events'
    | '/_app/explore'
    | '/_app/feed'
    | '/_app/gallery'
    | '/_app/journeys'
    | '/_app/knowledge'
    | '/_app/marketplace'
    | '/_app/me'
    | '/_app/wiring-harness'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_marketing/'
    | '/_app/me/inventory'
    | '/_app/me/notifications'
    | '/_app/me/settings'
    | '/_app/me/subscription'
    | '/_app/users/$username'
    | '/api/auth/$'
    | '/_app/cars/'
    | '/_app/journeys/'
    | '/_app/me/'
    | '/_app/users/$username/cars'
    | '/_app/users/$username/journeys'
    | '/_app/users/$username/'
    | '/_app/users/$username/cars/$slug'
    | '/_app/users/$username/cars/new'
    | '/_app/users/$username/journeys/$slug'
    | '/_app/users/$username/cars/'
    | '/_app/users/$username/journeys/'
    | '/_app/users/$username/cars/$slug/edit'
    | '/_app/users/$username/cars/$slug/'
    | '/_app/users/$username/journeys/$slug/'
    | '/_app/users/$username/journeys/$slug/v2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/wiring-harness': {
      id: '/_app/wiring-harness'
      path: '/wiring-harness'
      fullPath: '/wiring-harness'
      preLoaderRoute: typeof AppWiringHarnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journeys': {
      id: '/_app/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof AppJourneysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery': {
      id: '/_app/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cars': {
      id: '/_app/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof AppCarsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/': {
      id: '/_app/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/_app/journeys/': {
      id: '/_app/journeys/'
      path: '/'
      fullPath: '/journeys/'
      preLoaderRoute: typeof AppJourneysIndexRouteImport
      parentRoute: typeof AppJourneysRoute
    }
    '/_app/cars/': {
      id: '/_app/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof AppCarsIndexRouteImport
      parentRoute: typeof AppCarsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/$username': {
      id: '/_app/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AppUsersUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/subscription': {
      id: '/_app/me/subscription'
      path: '/subscription'
      fullPath: '/me/subscription'
      preLoaderRoute: typeof AppMeSubscriptionRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/_app/me/settings': {
      id: '/_app/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof AppMeSettingsRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/_app/me/notifications': {
      id: '/_app/me/notifications'
      path: '/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof AppMeNotificationsRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/_app/me/inventory': {
      id: '/_app/me/inventory'
      path: '/inventory'
      fullPath: '/me/inventory'
      preLoaderRoute: typeof AppMeInventoryRouteImport
      parentRoute: typeof AppMeRoute
    }
    '/_app/users/$username/': {
      id: '/_app/users/$username/'
      path: '/'
      fullPath: '/users/$username/'
      preLoaderRoute: typeof AppUsersUsernameIndexRouteImport
      parentRoute: typeof AppUsersUsernameRoute
    }
    '/_app/users/$username/journeys': {
      id: '/_app/users/$username/journeys'
      path: '/journeys'
      fullPath: '/users/$username/journeys'
      preLoaderRoute: typeof AppUsersUsernameJourneysRouteImport
      parentRoute: typeof AppUsersUsernameRoute
    }
    '/_app/users/$username/cars': {
      id: '/_app/users/$username/cars'
      path: '/cars'
      fullPath: '/users/$username/cars'
      preLoaderRoute: typeof AppUsersUsernameCarsRouteImport
      parentRoute: typeof AppUsersUsernameRoute
    }
    '/_app/users/$username/journeys/': {
      id: '/_app/users/$username/journeys/'
      path: '/'
      fullPath: '/users/$username/journeys/'
      preLoaderRoute: typeof AppUsersUsernameJourneysIndexRouteImport
      parentRoute: typeof AppUsersUsernameJourneysRoute
    }
    '/_app/users/$username/cars/': {
      id: '/_app/users/$username/cars/'
      path: '/'
      fullPath: '/users/$username/cars/'
      preLoaderRoute: typeof AppUsersUsernameCarsIndexRouteImport
      parentRoute: typeof AppUsersUsernameCarsRoute
    }
    '/_app/users/$username/journeys/$slug': {
      id: '/_app/users/$username/journeys/$slug'
      path: '/$slug'
      fullPath: '/users/$username/journeys/$slug'
      preLoaderRoute: typeof AppUsersUsernameJourneysSlugRouteImport
      parentRoute: typeof AppUsersUsernameJourneysRoute
    }
    '/_app/users/$username/cars/new': {
      id: '/_app/users/$username/cars/new'
      path: '/new'
      fullPath: '/users/$username/cars/new'
      preLoaderRoute: typeof AppUsersUsernameCarsNewRouteImport
      parentRoute: typeof AppUsersUsernameCarsRoute
    }
    '/_app/users/$username/cars/$slug': {
      id: '/_app/users/$username/cars/$slug'
      path: '/$slug'
      fullPath: '/users/$username/cars/$slug'
      preLoaderRoute: typeof AppUsersUsernameCarsSlugRouteImport
      parentRoute: typeof AppUsersUsernameCarsRoute
    }
    '/_app/users/$username/journeys/$slug/': {
      id: '/_app/users/$username/journeys/$slug/'
      path: '/'
      fullPath: '/users/$username/journeys/$slug/'
      preLoaderRoute: typeof AppUsersUsernameJourneysSlugIndexRouteImport
      parentRoute: typeof AppUsersUsernameJourneysSlugRoute
    }
    '/_app/users/$username/cars/$slug/': {
      id: '/_app/users/$username/cars/$slug/'
      path: '/'
      fullPath: '/users/$username/cars/$slug/'
      preLoaderRoute: typeof AppUsersUsernameCarsSlugIndexRouteImport
      parentRoute: typeof AppUsersUsernameCarsSlugRoute
    }
    '/_app/users/$username/cars/$slug/edit': {
      id: '/_app/users/$username/cars/$slug/edit'
      path: '/edit'
      fullPath: '/users/$username/cars/$slug/edit'
      preLoaderRoute: typeof AppUsersUsernameCarsSlugEditRouteImport
      parentRoute: typeof AppUsersUsernameCarsSlugRoute
    }
    '/_app/users/$username/journeys/$slug/v2/': {
      id: '/_app/users/$username/journeys/$slug/v2/'
      path: '/v2'
      fullPath: '/users/$username/journeys/$slug/v2/'
      preLoaderRoute: typeof AppUsersUsernameJourneysSlugV2IndexRouteImport
      parentRoute: typeof AppUsersUsernameJourneysSlugRoute
    }
  }
}

interface AppCarsRouteChildren {
  AppCarsIndexRoute: typeof AppCarsIndexRoute
}

const AppCarsRouteChildren: AppCarsRouteChildren = {
  AppCarsIndexRoute: AppCarsIndexRoute,
}

const AppCarsRouteWithChildren =
  AppCarsRoute._addFileChildren(AppCarsRouteChildren)

interface AppJourneysRouteChildren {
  AppJourneysIndexRoute: typeof AppJourneysIndexRoute
}

const AppJourneysRouteChildren: AppJourneysRouteChildren = {
  AppJourneysIndexRoute: AppJourneysIndexRoute,
}

const AppJourneysRouteWithChildren = AppJourneysRoute._addFileChildren(
  AppJourneysRouteChildren,
)

interface AppMeRouteChildren {
  AppMeInventoryRoute: typeof AppMeInventoryRoute
  AppMeNotificationsRoute: typeof AppMeNotificationsRoute
  AppMeSettingsRoute: typeof AppMeSettingsRoute
  AppMeSubscriptionRoute: typeof AppMeSubscriptionRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
}

const AppMeRouteChildren: AppMeRouteChildren = {
  AppMeInventoryRoute: AppMeInventoryRoute,
  AppMeNotificationsRoute: AppMeNotificationsRoute,
  AppMeSettingsRoute: AppMeSettingsRoute,
  AppMeSubscriptionRoute: AppMeSubscriptionRoute,
  AppMeIndexRoute: AppMeIndexRoute,
}

const AppMeRouteWithChildren = AppMeRoute._addFileChildren(AppMeRouteChildren)

interface AppUsersUsernameCarsSlugRouteChildren {
  AppUsersUsernameCarsSlugEditRoute: typeof AppUsersUsernameCarsSlugEditRoute
  AppUsersUsernameCarsSlugIndexRoute: typeof AppUsersUsernameCarsSlugIndexRoute
}

const AppUsersUsernameCarsSlugRouteChildren: AppUsersUsernameCarsSlugRouteChildren =
  {
    AppUsersUsernameCarsSlugEditRoute: AppUsersUsernameCarsSlugEditRoute,
    AppUsersUsernameCarsSlugIndexRoute: AppUsersUsernameCarsSlugIndexRoute,
  }

const AppUsersUsernameCarsSlugRouteWithChildren =
  AppUsersUsernameCarsSlugRoute._addFileChildren(
    AppUsersUsernameCarsSlugRouteChildren,
  )

interface AppUsersUsernameCarsRouteChildren {
  AppUsersUsernameCarsSlugRoute: typeof AppUsersUsernameCarsSlugRouteWithChildren
  AppUsersUsernameCarsNewRoute: typeof AppUsersUsernameCarsNewRoute
  AppUsersUsernameCarsIndexRoute: typeof AppUsersUsernameCarsIndexRoute
}

const AppUsersUsernameCarsRouteChildren: AppUsersUsernameCarsRouteChildren = {
  AppUsersUsernameCarsSlugRoute: AppUsersUsernameCarsSlugRouteWithChildren,
  AppUsersUsernameCarsNewRoute: AppUsersUsernameCarsNewRoute,
  AppUsersUsernameCarsIndexRoute: AppUsersUsernameCarsIndexRoute,
}

const AppUsersUsernameCarsRouteWithChildren =
  AppUsersUsernameCarsRoute._addFileChildren(AppUsersUsernameCarsRouteChildren)

interface AppUsersUsernameJourneysSlugRouteChildren {
  AppUsersUsernameJourneysSlugIndexRoute: typeof AppUsersUsernameJourneysSlugIndexRoute
  AppUsersUsernameJourneysSlugV2IndexRoute: typeof AppUsersUsernameJourneysSlugV2IndexRoute
}

const AppUsersUsernameJourneysSlugRouteChildren: AppUsersUsernameJourneysSlugRouteChildren =
  {
    AppUsersUsernameJourneysSlugIndexRoute:
      AppUsersUsernameJourneysSlugIndexRoute,
    AppUsersUsernameJourneysSlugV2IndexRoute:
      AppUsersUsernameJourneysSlugV2IndexRoute,
  }

const AppUsersUsernameJourneysSlugRouteWithChildren =
  AppUsersUsernameJourneysSlugRoute._addFileChildren(
    AppUsersUsernameJourneysSlugRouteChildren,
  )

interface AppUsersUsernameJourneysRouteChildren {
  AppUsersUsernameJourneysSlugRoute: typeof AppUsersUsernameJourneysSlugRouteWithChildren
  AppUsersUsernameJourneysIndexRoute: typeof AppUsersUsernameJourneysIndexRoute
}

const AppUsersUsernameJourneysRouteChildren: AppUsersUsernameJourneysRouteChildren =
  {
    AppUsersUsernameJourneysSlugRoute:
      AppUsersUsernameJourneysSlugRouteWithChildren,
    AppUsersUsernameJourneysIndexRoute: AppUsersUsernameJourneysIndexRoute,
  }

const AppUsersUsernameJourneysRouteWithChildren =
  AppUsersUsernameJourneysRoute._addFileChildren(
    AppUsersUsernameJourneysRouteChildren,
  )

interface AppUsersUsernameRouteChildren {
  AppUsersUsernameCarsRoute: typeof AppUsersUsernameCarsRouteWithChildren
  AppUsersUsernameJourneysRoute: typeof AppUsersUsernameJourneysRouteWithChildren
  AppUsersUsernameIndexRoute: typeof AppUsersUsernameIndexRoute
}

const AppUsersUsernameRouteChildren: AppUsersUsernameRouteChildren = {
  AppUsersUsernameCarsRoute: AppUsersUsernameCarsRouteWithChildren,
  AppUsersUsernameJourneysRoute: AppUsersUsernameJourneysRouteWithChildren,
  AppUsersUsernameIndexRoute: AppUsersUsernameIndexRoute,
}

const AppUsersUsernameRouteWithChildren =
  AppUsersUsernameRoute._addFileChildren(AppUsersUsernameRouteChildren)

interface AppRouteChildren {
  AppCarsRoute: typeof AppCarsRouteWithChildren
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFeedRoute: typeof AppFeedRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppJourneysRoute: typeof AppJourneysRouteWithChildren
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMeRoute: typeof AppMeRouteWithChildren
  AppWiringHarnessRoute: typeof AppWiringHarnessRoute
  AppUsersUsernameRoute: typeof AppUsersUsernameRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCarsRoute: AppCarsRouteWithChildren,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRoute,
  AppExploreRoute: AppExploreRoute,
  AppFeedRoute: AppFeedRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppJourneysRoute: AppJourneysRouteWithChildren,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMeRoute: AppMeRouteWithChildren,
  AppWiringHarnessRoute: AppWiringHarnessRoute,
  AppUsersUsernameRoute: AppUsersUsernameRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
