/**
 * API Client
 *
 * Re-exports generated API hooks with additional utilities.
 * All hooks are auto-generated by Orval from Swagger specification.
 *
 * Usage:
 * ```typescript
 * import { useGetApiUsersMeCars } from '@/lib/api'
 *
 * function MyComponent() {
 *   const { data, isLoading } = useGetApiUsersMeCars()
 *   // ...
 * }
 * ```
 */

export * from "@/generated/api";
export { apiFetcher } from "./client";
export { mobileQueryDefaults } from "./query-defaults";
