// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Paddokk.Data;

#nullable disable

namespace Paddokk.Data.Migrations
{
    [DbContext(typeof(PaddokkDbContext))]
    partial class PaddokkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Paddokk.Core.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultActiveJourneyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefaultActiveJourneyId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.CarGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("CarGenerations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 1,
                            Name = "A90",
                            StartYear = 2019
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 1,
                            EndYear = 2002,
                            Name = "A80",
                            StartYear = 1993
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 5,
                            EndYear = 2000,
                            Name = "EK",
                            StartYear = 1996
                        },
                        new
                        {
                            Id = 4,
                            CarModelId = 5,
                            EndYear = 2005,
                            Name = "EP3",
                            StartYear = 2001
                        },
                        new
                        {
                            Id = 5,
                            CarModelId = 9,
                            EndYear = 1994,
                            Name = "S13",
                            StartYear = 1989
                        },
                        new
                        {
                            Id = 6,
                            CarModelId = 9,
                            EndYear = 1998,
                            Name = "S14",
                            StartYear = 1995
                        },
                        new
                        {
                            Id = 7,
                            CarModelId = 13,
                            EndYear = 2006,
                            Name = "E46",
                            StartYear = 2000
                        },
                        new
                        {
                            Id = 8,
                            CarModelId = 13,
                            EndYear = 2013,
                            Name = "E92",
                            StartYear = 2007
                        });
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.CarMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarMakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Japan",
                            Group = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Japan",
                            Group = 1,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Japan",
                            Group = 1,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Japan",
                            Group = 1,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Japan",
                            Group = 1,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Germany",
                            Group = 2,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Germany",
                            Group = 2,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Germany",
                            Group = 2,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Germany",
                            Group = 2,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Germany",
                            Group = 2,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 11,
                            Country = "USA",
                            Group = 3,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 12,
                            Country = "USA",
                            Group = 3,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 13,
                            Country = "USA",
                            Group = 3,
                            Name = "Dodge"
                        });
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarMakeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CarMakeId", "Name")
                        .IsUnique();

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarMakeId = 1,
                            Name = "Supra"
                        },
                        new
                        {
                            Id = 2,
                            CarMakeId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 3,
                            CarMakeId = 1,
                            Name = "86"
                        },
                        new
                        {
                            Id = 4,
                            CarMakeId = 1,
                            Name = "MR2"
                        },
                        new
                        {
                            Id = 5,
                            CarMakeId = 2,
                            Name = "Civic"
                        },
                        new
                        {
                            Id = 6,
                            CarMakeId = 2,
                            Name = "S2000"
                        },
                        new
                        {
                            Id = 7,
                            CarMakeId = 2,
                            Name = "NSX"
                        },
                        new
                        {
                            Id = 8,
                            CarMakeId = 2,
                            Name = "Integra"
                        },
                        new
                        {
                            Id = 9,
                            CarMakeId = 3,
                            Name = "240SX"
                        },
                        new
                        {
                            Id = 10,
                            CarMakeId = 3,
                            Name = "GT-R"
                        },
                        new
                        {
                            Id = 11,
                            CarMakeId = 3,
                            Name = "350Z"
                        },
                        new
                        {
                            Id = 12,
                            CarMakeId = 3,
                            Name = "370Z"
                        },
                        new
                        {
                            Id = 13,
                            CarMakeId = 6,
                            Name = "M3"
                        },
                        new
                        {
                            Id = 14,
                            CarMakeId = 6,
                            Name = "M4"
                        },
                        new
                        {
                            Id = 15,
                            CarMakeId = 6,
                            Name = "335i"
                        },
                        new
                        {
                            Id = 16,
                            CarMakeId = 11,
                            Name = "Mustang"
                        },
                        new
                        {
                            Id = 17,
                            CarMakeId = 11,
                            Name = "Focus"
                        });
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCarId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserCarId");

                    b.HasIndex("UserId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneyLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JourneyId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("UserId", "JourneyId")
                        .IsUnique();

                    b.ToTable("JourneyLikes");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneyPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<int>("JourneyId")
                        .HasColumnType("integer");

                    b.Property<string>("TextContent")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("UserId");

                    b.ToTable("JourneyPosts");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneyPostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("JourneyPostId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JourneyPostId");

                    b.ToTable("JourneyPostImages");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneySubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JourneyId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("UserId", "JourneyId")
                        .IsUnique();

                    b.ToTable("JourneySubscriptions");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<int>("JourneyPostId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JourneyPostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarGenerationId")
                        .HasColumnType("integer");

                    b.Property<int?>("CarMakeId")
                        .HasColumnType("integer");

                    b.Property<int?>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomBuildName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCustomBuild")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SearchText")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarGenerationId");

                    b.HasIndex("CarMakeId");

                    b.HasIndex("CarModelId");

                    b.HasIndex("SearchText");

                    b.HasIndex("UserId");

                    b.ToTable("UserCars");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MediumUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserCarId")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserCarId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = true");

                    b.ToTable("UserCarImages");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCarLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCarId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserCarId");

                    b.HasIndex("UserId", "UserCarId")
                        .IsUnique();

                    b.ToTable("UserCarLikes");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCarSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("UserCarId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserCarId");

                    b.HasIndex("UserId", "UserCarId")
                        .IsUnique();

                    b.ToTable("UserCarSubscriptions");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.Journey", "DefaultActiveJourney")
                        .WithMany()
                        .HasForeignKey("DefaultActiveJourneyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultActiveJourney");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.CarGeneration", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.CarModel", "CarModel")
                        .WithMany("Generations")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.CarModel", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.CarMake", "CarMake")
                        .WithMany("Models")
                        .HasForeignKey("CarMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarMake");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.Journey", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.UserCar", "UserCar")
                        .WithMany("Journeys")
                        .HasForeignKey("UserCarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paddokk.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany("Journeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserCar");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneyLike", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.Journey", "Journey")
                        .WithMany("Likes")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paddokk.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany("JourneyLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneyPost", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.Journey", "Journey")
                        .WithMany("Posts")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paddokk.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneyPostImage", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.JourneyPost", "JourneyPost")
                        .WithMany("Images")
                        .HasForeignKey("JourneyPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JourneyPost");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneySubscription", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.Journey", "Journey")
                        .WithMany("Subscriptions")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paddokk.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany("JourneySubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.PostComment", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.JourneyPost", "JourneyPost")
                        .WithMany("Comments")
                        .HasForeignKey("JourneyPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paddokk.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JourneyPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCar", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.CarGeneration", "CarGeneration")
                        .WithMany()
                        .HasForeignKey("CarGenerationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paddokk.Core.Models.Entities.CarMake", "CarMake")
                        .WithMany()
                        .HasForeignKey("CarMakeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paddokk.Core.Models.Entities.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Paddokk.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarGeneration");

                    b.Navigation("CarMake");

                    b.Navigation("CarModel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCarImage", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.UserCar", "UserCar")
                        .WithMany("Images")
                        .HasForeignKey("UserCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCar");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCarLike", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.UserCar", "UserCar")
                        .WithMany("Likes")
                        .HasForeignKey("UserCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paddokk.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany("UserCarLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserCar");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCarSubscription", b =>
                {
                    b.HasOne("Paddokk.Core.Models.Entities.UserCar", "UserCar")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paddokk.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany("UserCarSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserCar");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Comments");

                    b.Navigation("JourneyLikes");

                    b.Navigation("JourneySubscriptions");

                    b.Navigation("Journeys");

                    b.Navigation("UserCarLikes");

                    b.Navigation("UserCarSubscriptions");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.CarMake", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.CarModel", b =>
                {
                    b.Navigation("Generations");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.Journey", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Posts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.JourneyPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Paddokk.Core.Models.Entities.UserCar", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Journeys");

                    b.Navigation("Likes");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
